### PR TITLE
Documentation of main functions & more

### PR DESCRIPTION
**Pull request by pepaaran**
This pull request includes:
- completed documentation of the P-model related functions (not lm3ppa)
- fixed tidyr::unnest() errors in the cost functions and vignettes
- eliminates obsolete cost functions
- introduces a vignette for cost function documentation (still in the making).

### CODE REVIEW

**Comment by stineb** [comment]
Thanks @pepaaran ! Before merging, can we sort out the failing checks by installing BayesianTools from github instead of CRAN during the checks?

**Comment by khufkens** [comment]
Hi Pepa, I see some error on documentation (not related to the BT issue).

You might want to run goodpractice::gp() on the code on a regular basis. The lintr package will also streamline coding as it flags common errors.

**Comment by pepaaran** [comment]
Thanks Koen, I think the documentation error was fixed, but I didn't know how to check if it was solved without running the checks again. So thanks for the pointers!

**Comment by khufkens** [comment]
Hi @pepaaran, you should be able to look at the details of every failed check. There you can see if there are notes or warnings (not related to BT). All of them should be addressed before moving forward. I think I emailed you the notes on brittle code, this was part of it. Basically you should make sure things work out, before I will merge. Otherwise I'll have to deal with all these issues (forwarding work and potentially changes I'm not up to date with to others - me in this case, but others generally).

**Pull request merged**
