### PR TITLE
Documentation of example drivers and validation data

### PR DESCRIPTION
**Pull request by pepaaran**

### CODE REVIEW

**Comment by stineb** [comment]
The build fails with the following error:
```
ERROR: dependency ‘BayesianTools’ is not available for package ‘rsofun’
```
Indeed, the package has been removed from CRAN, see [here](https://cran.r-project.org/web/packages/BayesianTools/index.html). Not sure what's going on.  Can you drop Florian Hartig a line to ask whether there are plans to continue maintain it and have it on CRAN again in the future @pepaaran ? Thx.

**Comment by stineb** [comment]
I left a note as an issue on the BayesianTools repo ([link](https://github.com/florianhartig/BayesianTools/issues/243#issue-1414518771)).

**Comment by pepaaran** [comment]
Should I still contact Florian?

**Comment by stineb** [comment]
Yes, dropping him an email wouldn't hurt. You can refer to the issue I left on his repo.

**Pull request merged**
